export const LOAD_REQUESTED = 'APP/BROWSER/LOAD_REQUESTED';
export const LOAD_RESOLVED = 'APP/BROWSER/LOAD_RESOLVED';
export const LOAD_REJECTED = 'APP/BROWSER/LOAD_REJECTED';

export const PAYLOAD_SET = 'APP/EDITOR/PAYLOAD_SET';
