export const REQUEST_SEND = 'APP/CRUD/REQUEST/SEND';
export const REQUEST_GET_ONE = 'APP/CRUD/REQUEST/GET_ONE';
export const REQUEST_GET_LIST = 'APP/CRUD/REQUEST/GET_LIST';
export const REQUEST_CREATE = 'APP/CRUD/REQUEST/CREATE';
export const REQUEST_UPDATE = 'APP/CRUD/REQUEST/UPDATE';
export const REQUEST_REMOVE = 'APP/CRUD/REQUEST/REMOVE';

export const RESPONSE_SUCCESS = 'APP/CRUD/RESPONSE/SUCCESS';
export const RESPONSE_ERROR = 'APP/CRUD/RESPONSE/ERROR';

export const SET_QUERY_PARAMS = 'APP/CRUD/SET_PARAMS';
