export const styles = theme => ({
  root: {
    maxWidth: 250,
    minWidth: 200,
    height: '100vh',
    backgroundColor: '#343434',
    paddingTop: 20,
    boxShadow: '1px 1px 5px grey',
    fontFamily: 'monospace',
    fontSize: 16,
  },
  title: {
    fontFamily: 'Text Me One',
    color: '#f8fff4',
    textAlign: 'center',
    fontSize: 32,
    borderWidth: '0 0 1px 0',
    borderStyle: 'solid',
    borderColor: '#673333',
    paddingBottom: 15,
    marginBottom: 15,
  },
  itemText: {
    color: '#e2e8de',
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 5,
  },
  listItem: {
    color: '#a8ada6',
    padding: 0,
    paddingLeft: 20,
    cursor: 'pointer',
  },
  menuIcon: {
    marginRight: 3,
    color: '#a8ada6',
    fontSize: 12,
    marginBottom: 2,
  },
  itemTextNested: {
    padding: 0,
    color: '#c4c9c1',
    marginLeft: theme.spacing.unit * 3,
    marginRight: 2,
  },
  expandable: {
    color: '#939790',
    paddingRight: 8,
    marginRight: 5,
  },
  nested: {
    fontSize: 14,
    width: 'calc(100% - 2px)',
    boxShadow: '0px 0px 1px 0px #444444',
    backgroundColor: '#2b2b2b',
  },
  navLink: {
    textDecoration: 'none',
    color: theme.palette.common.black,
  },
});
