export const styles = theme => ({
  root: {
    padding: 0,
    height: '100%',
  },
  rightPane: {
    height: '100vh',
    padding: 20,
    paddingTop: 15,
    paddingBottom: 0,
    backgroundColor: '#343434',
    boxShadow: '-1px 0px 1px grey',
  },
  leftPane: {
    height: '100vh',
  },
  rightPaneTitle: {
    height: 40,
    fontSize: 24,
    textAlign: 'right',
    textTransform: 'uppercase',
    color: '#202020',
    letterSpacing: 3,
    textShadow: '-1px -1px 1px #222222, 2px 2px 1px #404040',
  },
  responseTitle: {
    borderBottomColor: '#673333',
    borderWidth: '0 0 1px 0',
    borderStyle: 'solid',
  },
  actionWrapper: {
    marginRight: 60,
    width: '100%',
    display: 'flex',
    flexFlow: 'column',
  },
  actionContainer: {
    boxShadow: '-1px 0px 1px grey',
    borderRadius: 5,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    flex: 1,
    zIndex: 2,
    padding: 10,
    position: 'fixed',
    bottom: 0,
    left: '30%',
    width: 50,
    background: 'red', // '#343434',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#b4b4b4',
    borderTop: 0,
  },
  actionIcon: {
    color: theme.palette.primary.contrastText,
  },
  formControl: {
    marginLeft: 30,
    backgroundColor: '#FFFFFF',
    margin: theme.spacing.unit,
  },
});
