export const LOAD_REQUESTED = 'APP/CORE/LOAD_ONE_REQUESTED';
export const LOAD_RESOLVED = 'APP/CORE/LOAD_ONE_RESOLVED';
export const LOAD_REJECTED = 'APP/CORE/LOAD_ONE_REJECTED';

export const SAVE_REQUESTED = 'APP/CORE/SAVE_REQUESTED';
export const SAVE_RESOLVED = 'APP/CORE/SAVE_RESOLVED';
export const SAVE_REJECTED = 'APP/CORE/SAVE_REJECTED';
